import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import { UserInfo } from "components/aside/UserInfo";
import { NewChats } from "components/aside/NewChats";
import { SearchBar } from "components/aside/SearchBar";
import { useUserSession } from "hooks/useUserSession";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await useUserSession();
  return (
    <html lang="es">
      <Providers>
        <body className={`flex ${inter.className}`}>
          <aside className=" bg-[#f9f9f9] col-span-2 flex flex-col p-4 gap-4 h-full">
            <UserInfo />
            <SearchBar />
            <NewChats session={session} />
          </aside>
          <div
            id="first-child"
            className="flex-1 flex flex-col  h-full relative p-4 gap-4"
          >
            {children}
          </div>
        </body>
      </Providers>
    </html>
  );
}
